name: Apply generated configuration to local Kong gateway and update API documentation

on:
  push:
    branches:
      - master

jobs:
  deploy_to_kong:
    runs-on: ubuntu-latest
    name: Apply generated configuration to local Kong gateway and update API documentation
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup inso
        uses: kong/setup-inso@v1
        with:
          inso-version: 3.5.0
      - name: Install Kong Deck CLI
        uses: kong/setup-deck@v1
      - name: Install httpie 
        run: | 
          sudo apt-get update 
          sudo apt-get install -y httpie
      - name: Generate Kong declarative configuration from Spec
        run: inso generate config ./openapi/orders.yaml --type declarative > kong2.x.yaml
      - name: Convert configuration for 3.0
        run: deck convert --from kong-gateway-2.x --to kong-gateway-3.x --input-file kong2.x.yaml --output-file kong3-b.x.yaml
      - name: Connect to Kong instance 
        run: deck ping --kong-addr "$(echo $KONG_ADMIN_URL)"
      - name: fix temporary regex issue 
        run: sed 's/\\//' kong3-b.x.yaml > kong3.x.yaml
      - name: Validate Kong declarative configuration
        run: deck validate -s kong3.x.yaml
      - name: Deploy declarative config
        run: deck sync -s kong3.x.yaml --kong-addr "$(echo $KONG_ADMIN_URL)"
      # - name: Publish Spec to Dev Portal
      # run: cd ./openapi && http --check-status --ignore-stdin PUT http://16.16.254.147:8001/default/files/specs/orders.yaml contents=@orders.yaml
